# Generated by Django 6.0.6 on 2026-06-10 07:16

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('leads', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PDFImport',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('file_path', models.CharField(help_text='Path to the uploaded PDF file', max_length=500, verbose_name='File Path')),
                ('file_name', models.CharField(blank=True, help_text='Original file name', max_length=255, verbose_name='File Name')),
                ('file_size', models.IntegerField(blank=True, help_text='File size in bytes', null=True, verbose_name='File Size')),
                ('pages_count', models.IntegerField(blank=True, help_text='Number of pages in PDF', null=True, verbose_name='Pages Count')),
                ('imported_at', models.DateTimeField(auto_now_add=True, help_text='When file was uploaded', verbose_name='Imported At')),
                ('extraction_status', models.CharField(choices=[('PENDING', 'Pending'), ('PROCESSING', 'Processing'), ('COMPLETED', 'Completed'), ('FAILED', 'Failed')], db_index=True, default='PENDING', help_text='Current extraction status', max_length=20, verbose_name='Extraction Status')),
                ('processed_at', models.DateTimeField(blank=True, help_text='When extraction was completed', null=True, verbose_name='Processed At')),
                ('extracted_text', models.TextField(blank=True, help_text='Full text extracted from PDF', null=True, verbose_name='Extracted Text')),
                ('extracted_data', models.TextField(blank=True, help_text='Structured data extracted from PDF (JSON format). Use JSONField with PostgreSQL.', null=True, verbose_name='Extracted Data')),
                ('error_message', models.TextField(blank=True, help_text='Error details if extraction failed', verbose_name='Error Message')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('batch', models.OneToOneField(help_text='Associated batch', on_delete=django.db.models.deletion.CASCADE, related_name='pdf_import', to='leads.batch', verbose_name='Batch')),
                ('created_by', models.ForeignKey(help_text='User who initiated the import', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pdf_imports', to=settings.AUTH_USER_MODEL, verbose_name='Created By')),
            ],
            options={
                'verbose_name': 'PDF Import',
                'verbose_name_plural': 'PDF Imports',
                'db_table': 'pdf_import',
                'ordering': ['-imported_at'],
            },
        ),
        migrations.CreateModel(
            name='PDFExtractedData',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('page_number', models.IntegerField(help_text='Page number in PDF', verbose_name='Page Number')),
                ('customer_name', models.CharField(blank=True, help_text='Extracted customer name', max_length=200, verbose_name='Customer Name')),
                ('phone', models.CharField(blank=True, db_index=True, help_text='Extracted phone number', max_length=15, verbose_name='Phone Number')),
                ('email', models.EmailField(blank=True, help_text='Extracted email address', max_length=254, verbose_name='Email')),
                ('loan_amount', models.DecimalField(blank=True, decimal_places=2, help_text='Extracted loan amount', max_digits=15, null=True, verbose_name='Loan Amount')),
                ('confidence_score', models.FloatField(default=0.0, help_text='OCR/extraction confidence (0-1)', verbose_name='Confidence Score')),
                ('extracted_fields', models.TextField(blank=True, help_text='All extracted fields in JSON format. Use JSONField with PostgreSQL.', null=True, verbose_name='Extracted Fields')),
                ('is_processed', models.BooleanField(db_index=True, default=False, help_text='Whether this data has been converted to a lead', verbose_name='Is Processed')),
                ('created_lead_id', models.CharField(blank=True, help_text='ID of created lead (if processed)', max_length=100, verbose_name='Created Lead ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('pdf_import', models.ForeignKey(help_text='Source PDF import', on_delete=django.db.models.deletion.CASCADE, related_name='extracted_leads', to='pdf.pdfimport', verbose_name='PDF Import')),
            ],
            options={
                'verbose_name': 'PDF Extracted Data',
                'verbose_name_plural': 'PDF Extracted Data',
                'db_table': 'pdf_extracted_data',
                'ordering': ['page_number'],
            },
        ),
        migrations.AddIndex(
            model_name='pdfimport',
            index=models.Index(fields=['extraction_status'], name='pdf_status_idx'),
        ),
        migrations.AddIndex(
            model_name='pdfimport',
            index=models.Index(fields=['created_by'], name='pdf_created_by_idx'),
        ),
        migrations.AddIndex(
            model_name='pdfextracteddata',
            index=models.Index(fields=['pdf_import', 'is_processed'], name='pdf_data_import_processed_idx'),
        ),
        migrations.AddIndex(
            model_name='pdfextracteddata',
            index=models.Index(fields=['phone'], name='pdf_data_phone_idx'),
        ),
        migrations.AddIndex(
            model_name='pdfextracteddata',
            index=models.Index(fields=['is_processed'], name='pdf_data_processed_idx'),
        ),
    ]
