# Generated by Django 4.2.12 on 2026-06-10 11:37

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('pdf', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PDFPage',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('page_number', models.IntegerField(verbose_name='Page Number')),
                ('image_path', models.CharField(help_text='Path to the rendered page image', max_length=500, verbose_name='Image Path')),
                ('thumbnail_path', models.CharField(blank=True, help_text='Path to the page thumbnail image', max_length=500, verbose_name='Thumbnail Path')),
                ('width', models.IntegerField(default=0, help_text='Image width in pixels', verbose_name='Width')),
                ('height', models.IntegerField(default=0, help_text='Image height in pixels', verbose_name='Height')),
                ('file_size', models.IntegerField(default=0, help_text='Image file size in bytes', verbose_name='File Size')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('pdf_import', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pages', to='pdf.pdfimport', verbose_name='PDF Import')),
            ],
            options={
                'verbose_name': 'PDF Page',
                'verbose_name_plural': 'PDF Pages',
                'db_table': 'pdf_page',
                'ordering': ['page_number'],
                'indexes': [models.Index(fields=['pdf_import', 'page_number'], name='pdf_page_import_num_idx')],
                'unique_together': {('pdf_import', 'page_number')},
            },
        ),
    ]
