# Generated by Django 6.0.6 on 2026-06-10 07:16

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BankSource',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(db_index=True, help_text='Official name of the bank/financial institution', max_length=150, unique=True, verbose_name='Bank Name')),
                ('source_code', models.CharField(choices=[('HDFC', 'HDFC Bank'), ('ICICI', 'ICICI Bank'), ('AXIS', 'Axis Bank'), ('TATA_CAPITAL', 'Tata Capital'), ('OTHER', 'Other Banks')], db_index=True, help_text='Unique identifier for the source (HDFC, ICICI, etc.)', max_length=20, unique=True, verbose_name='Source Code')),
                ('contact_person', models.CharField(blank=True, help_text='Primary contact person at the bank', max_length=150, verbose_name='Contact Person')),
                ('email', models.EmailField(blank=True, help_text="Bank's official email address", max_length=254, verbose_name='Email')),
                ('phone', models.CharField(blank=True, help_text="Bank's contact phone number", max_length=15, verbose_name='Phone Number')),
                ('address', models.TextField(blank=True, help_text='Office address of the bank', verbose_name='Address')),
                ('city', models.CharField(blank=True, max_length=100, verbose_name='City')),
                ('state', models.CharField(blank=True, max_length=100, verbose_name='State')),
                ('is_active', models.BooleanField(db_index=True, default=True, help_text='Inactive sources will not be available for lead assignment', verbose_name='Is Active')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
            ],
            options={
                'verbose_name': 'Bank Source',
                'verbose_name_plural': 'Bank Sources',
                'db_table': 'leads_bank_source',
                'ordering': ['name'],
                'indexes': [models.Index(fields=['source_code'], name='bank_source_code_idx'), models.Index(fields=['is_active'], name='bank_is_active_idx')],
            },
        ),
        migrations.CreateModel(
            name='Campaign',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(help_text='Name of the marketing campaign', max_length=200, verbose_name='Campaign Name')),
                ('campaign_code', models.CharField(db_index=True, help_text='Unique identifier for the campaign', max_length=50, unique=True, verbose_name='Campaign Code')),
                ('status', models.CharField(choices=[('ACTIVE', 'Active'), ('INACTIVE', 'Inactive'), ('PAUSED', 'Paused'), ('COMPLETED', 'Completed')], db_index=True, default='ACTIVE', help_text='Current status of the campaign', max_length=20, verbose_name='Status')),
                ('description', models.TextField(blank=True, help_text='Campaign details and objectives', verbose_name='Description')),
                ('start_date', models.DateField(db_index=True, help_text='Campaign start date', verbose_name='Start Date')),
                ('end_date', models.DateField(blank=True, help_text='Campaign end date (if applicable)', null=True, verbose_name='End Date')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('bank_source', models.ForeignKey(help_text='Bank/source associated with this campaign', on_delete=django.db.models.deletion.PROTECT, related_name='campaigns', to='leads.banksource', verbose_name='Bank Source')),
                ('created_by', models.ForeignKey(help_text='User who created the campaign', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='campaigns_created', to=settings.AUTH_USER_MODEL, verbose_name='Created By')),
            ],
            options={
                'verbose_name': 'Campaign',
                'verbose_name_plural': 'Campaigns',
                'db_table': 'leads_campaign',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Batch',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('batch_number', models.CharField(db_index=True, help_text='Unique identifier for the batch', max_length=50, unique=True, verbose_name='Batch Number')),
                ('source_file_path', models.CharField(help_text='Path to the uploaded file', max_length=500, verbose_name='Source File Path')),
                ('import_status', models.CharField(choices=[('PENDING', 'Pending'), ('PROCESSING', 'Processing'), ('COMPLETED', 'Completed'), ('FAILED', 'Failed'), ('PARTIAL', 'Partial')], db_index=True, default='PENDING', help_text='Current status of the import', max_length=20, verbose_name='Import Status')),
                ('file_type', models.CharField(choices=[('EXCEL', 'Excel'), ('PDF', 'PDF'), ('CSV', 'CSV'), ('IMAGE', 'Image')], help_text='Type of file imported', max_length=20, verbose_name='File Type')),
                ('total_records', models.IntegerField(default=0, help_text='Total number of records in the batch', verbose_name='Total Records')),
                ('processed_records', models.IntegerField(default=0, help_text='Number of successfully processed records', verbose_name='Processed Records')),
                ('failed_records', models.IntegerField(default=0, help_text='Number of records that failed to import', verbose_name='Failed Records')),
                ('import_date', models.DateTimeField(auto_now_add=True, db_index=True, help_text='Date and time of import', verbose_name='Import Date')),
                ('processed_date', models.DateTimeField(blank=True, help_text='Date and time when import completed', null=True, verbose_name='Processed Date')),
                ('error_log', models.TextField(blank=True, help_text='Details of import errors in JSON format. Use JSONField with PostgreSQL.', null=True, verbose_name='Error Log')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('processed_by', models.ForeignKey(blank=True, help_text='User who processed the batch', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='batches_processed', to=settings.AUTH_USER_MODEL, verbose_name='Processed By')),
                ('uploaded_by', models.ForeignKey(help_text='User who uploaded the batch', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='batches_uploaded', to=settings.AUTH_USER_MODEL, verbose_name='Uploaded By')),
                ('campaign', models.ForeignKey(help_text='Campaign associated with this batch', on_delete=django.db.models.deletion.PROTECT, related_name='batches', to='leads.campaign', verbose_name='Campaign')),
            ],
            options={
                'verbose_name': 'Batch',
                'verbose_name_plural': 'Batches',
                'db_table': 'leads_batch',
                'ordering': ['-import_date'],
            },
        ),
        migrations.CreateModel(
            name='Lead',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('lead_number', models.CharField(db_index=True, help_text='Unique identifier for the lead', max_length=50, unique=True, verbose_name='Lead Number')),
                ('lead_source_id', models.CharField(blank=True, help_text='External ID from the source system (e.g., HDFC_001_12345)', max_length=100, verbose_name='Lead Source ID')),
                ('customer_name', models.CharField(db_index=True, help_text='Full name of the customer', max_length=200, verbose_name='Customer Name')),
                ('phone', models.CharField(db_index=True, help_text='Primary contact phone number', max_length=15, verbose_name='Phone Number')),
                ('email', models.EmailField(blank=True, db_index=True, help_text='Email address of the customer', max_length=254, null=True, verbose_name='Email Address')),
                ('pan_number', models.CharField(blank=True, db_index=True, help_text='Permanent Account Number (10 digits)', max_length=10, null=True, verbose_name='PAN Number')),
                ('loan_amount', models.DecimalField(blank=True, decimal_places=2, help_text='Requested loan amount in INR', max_digits=15, null=True, verbose_name='Loan Amount')),
                ('loan_type', models.CharField(blank=True, choices=[('HOME', 'Home Loan'), ('PERSONAL', 'Personal Loan'), ('BUSINESS', 'Business Loan'), ('AUTO', 'Auto Loan'), ('EDUCATION', 'Education Loan'), ('GOLD', 'Gold Loan'), ('OTHER', 'Other')], help_text='Type of loan requested', max_length=20, verbose_name='Loan Type')),
                ('property_value', models.DecimalField(blank=True, decimal_places=2, help_text='Property value (for home loans)', max_digits=15, null=True, verbose_name='Property Value')),
                ('employment_type', models.CharField(blank=True, choices=[('SALARIED', 'Salaried'), ('SELF_EMPLOYED', 'Self Employed'), ('BUSINESS', 'Business'), ('AGRICULTURE', 'Agriculture'), ('UNEMPLOYED', 'Unemployed'), ('RETIRED', 'Retired'), ('OTHER', 'Other')], help_text='Type of employment', max_length=20, verbose_name='Employment Type')),
                ('address', models.TextField(help_text='Full postal address of the customer', verbose_name='Address')),
                ('city', models.CharField(db_index=True, help_text='City of residence', max_length=100, verbose_name='City')),
                ('state', models.CharField(db_index=True, help_text='State of residence', max_length=100, verbose_name='State')),
                ('pincode', models.CharField(blank=True, help_text='Postal code', max_length=10, verbose_name='Pincode')),
                ('lead_status', models.CharField(choices=[('NEW', 'New'), ('CONTACTED', 'Contacted'), ('QUALIFIED', 'Qualified'), ('CONVERTED', 'Converted'), ('REJECTED', 'Rejected'), ('LOST', 'Lost'), ('REACTIVATED', 'Reactivated')], db_index=True, default='NEW', help_text='Current status of the lead in the pipeline', max_length=20, verbose_name='Lead Status')),
                ('priority', models.CharField(choices=[('HIGH', 'High'), ('MEDIUM', 'Medium'), ('LOW', 'Low')], db_index=True, default='MEDIUM', help_text='Lead priority level', max_length=10, verbose_name='Priority')),
                ('assigned_at', models.DateTimeField(blank=True, help_text='When the lead was assigned', null=True, verbose_name='Assigned At')),
                ('is_duplicate', models.BooleanField(db_index=True, default=False, help_text='Whether this lead is marked as duplicate', verbose_name='Is Duplicate')),
                ('notes_summary', models.TextField(blank=True, help_text='Quick summary of notes (auto-updated)', verbose_name='Notes Summary')),
                ('is_deleted', models.BooleanField(db_index=True, default=False, help_text='Soft delete flag', verbose_name='Is Deleted')),
                ('deleted_at', models.DateTimeField(blank=True, help_text='When the lead was deleted', null=True, verbose_name='Deleted At')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('assigned_to', models.ForeignKey(blank=True, help_text='User responsible for this lead', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_leads', to=settings.AUTH_USER_MODEL, verbose_name='Assigned To')),
                ('batch', models.ForeignKey(help_text='Batch from which this lead was imported', on_delete=django.db.models.deletion.PROTECT, related_name='leads', to='leads.batch', verbose_name='Batch')),
                ('duplicate_of', models.ForeignKey(blank=True, help_text='Link to the original lead if duplicate', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='duplicates', to='leads.lead', verbose_name='Duplicate Of')),
            ],
            options={
                'verbose_name': 'Lead',
                'verbose_name_plural': 'Leads',
                'db_table': 'leads_lead',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='LeadAssignment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('assignment_status', models.CharField(choices=[('ACTIVE', 'Active'), ('COMPLETED', 'Completed'), ('TRANSFERRED', 'Transferred'), ('REJECTED', 'Rejected')], db_index=True, default='ACTIVE', help_text='Current status of the assignment', max_length=20, verbose_name='Assignment Status')),
                ('start_date', models.DateTimeField(auto_now_add=True, db_index=True, help_text='When the assignment started', verbose_name='Start Date')),
                ('end_date', models.DateTimeField(blank=True, help_text='When the assignment ended', null=True, verbose_name='End Date')),
                ('reason_for_transfer', models.TextField(blank=True, help_text='Reason if lead was transferred', verbose_name='Reason for Transfer')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('assigned_by', models.ForeignKey(help_text='User who made the assignment (usually Team Lead)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assignments_made', to=settings.AUTH_USER_MODEL, verbose_name='Assigned By')),
                ('assigned_to', models.ForeignKey(help_text='User this lead is assigned to (Caller/Operator)', on_delete=django.db.models.deletion.CASCADE, related_name='lead_assignments', to=settings.AUTH_USER_MODEL, verbose_name='Assigned To')),
                ('lead', models.ForeignKey(help_text='Lead being assigned', on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to='leads.lead', verbose_name='Lead')),
            ],
            options={
                'verbose_name': 'Lead Assignment',
                'verbose_name_plural': 'Lead Assignments',
                'db_table': 'leads_assignment',
                'ordering': ['-start_date'],
            },
        ),
        migrations.CreateModel(
            name='Outcome',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('outcome_type', models.CharField(choices=[('CONVERTED', 'Converted'), ('REJECTED', 'Rejected'), ('LOST', 'Lost'), ('PENDING', 'Pending'), ('FOLLOW_UP_REQUIRED', 'Follow-up Required')], db_index=True, help_text='Type of outcome', max_length=20, verbose_name='Outcome Type')),
                ('reason', models.CharField(blank=True, choices=[('HIGH_INTEREST', 'High Interest Rates'), ('POOR_CIBIL', 'Poor CIBIL Score'), ('INSUFFICIENT_INCOME', 'Insufficient Income'), ('EXISTING_LOANS', 'Existing Loans'), ('DOCUMENTATION', 'Documentation Issues'), ('OTHER', 'Other')], help_text='Reason for rejection/loss', max_length=50, verbose_name='Reason')),
                ('converted_amount', models.DecimalField(blank=True, decimal_places=2, help_text='Amount sanctioned (for conversions)', max_digits=15, null=True, verbose_name='Converted Amount')),
                ('conversion_date', models.DateField(blank=True, help_text='Date of conversion', null=True, verbose_name='Conversion Date')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('lead', models.ForeignKey(help_text='Associated lead', on_delete=django.db.models.deletion.CASCADE, related_name='outcomes', to='leads.lead', verbose_name='Lead')),
            ],
            options={
                'verbose_name': 'Outcome',
                'verbose_name_plural': 'Outcomes',
                'db_table': 'leads_outcome',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='campaign',
            index=models.Index(fields=['bank_source', 'status'], name='campaign_bank_status_idx'),
        ),
        migrations.AddIndex(
            model_name='campaign',
            index=models.Index(fields=['campaign_code'], name='campaign_code_idx'),
        ),
        migrations.AddIndex(
            model_name='campaign',
            index=models.Index(fields=['status'], name='campaign_status_idx'),
        ),
        migrations.AddIndex(
            model_name='batch',
            index=models.Index(fields=['campaign', 'import_status'], name='batch_campaign_status_idx'),
        ),
        migrations.AddIndex(
            model_name='batch',
            index=models.Index(fields=['batch_number'], name='batch_number_idx'),
        ),
        migrations.AddIndex(
            model_name='batch',
            index=models.Index(fields=['import_status'], name='batch_status_idx'),
        ),
        migrations.AddIndex(
            model_name='lead',
            index=models.Index(fields=['customer_name', 'phone'], name='lead_customer_phone_idx'),
        ),
        migrations.AddIndex(
            model_name='lead',
            index=models.Index(fields=['phone'], name='lead_phone_idx'),
        ),
        migrations.AddIndex(
            model_name='lead',
            index=models.Index(fields=['email'], name='lead_email_idx'),
        ),
        migrations.AddIndex(
            model_name='lead',
            index=models.Index(fields=['pan_number'], name='lead_pan_idx'),
        ),
        migrations.AddIndex(
            model_name='lead',
            index=models.Index(fields=['batch', 'lead_status'], name='lead_batch_status_idx'),
        ),
        migrations.AddIndex(
            model_name='lead',
            index=models.Index(fields=['assigned_to'], name='lead_assigned_to_idx'),
        ),
        migrations.AddIndex(
            model_name='lead',
            index=models.Index(fields=['is_deleted'], name='lead_is_deleted_idx'),
        ),
        migrations.AddIndex(
            model_name='lead',
            index=models.Index(fields=['lead_status'], name='lead_status_idx'),
        ),
        migrations.AddIndex(
            model_name='lead',
            index=models.Index(fields=['priority'], name='lead_priority_idx'),
        ),
        migrations.AddIndex(
            model_name='leadassignment',
            index=models.Index(fields=['lead', 'assigned_to'], name='assign_lead_user_idx'),
        ),
        migrations.AddIndex(
            model_name='leadassignment',
            index=models.Index(fields=['assigned_to', 'assignment_status'], name='assign_user_status_idx'),
        ),
        migrations.AddIndex(
            model_name='leadassignment',
            index=models.Index(fields=['assignment_status'], name='assign_status_idx'),
        ),
        migrations.AddIndex(
            model_name='outcome',
            index=models.Index(fields=['lead'], name='outcome_lead_idx'),
        ),
        migrations.AddIndex(
            model_name='outcome',
            index=models.Index(fields=['outcome_type'], name='outcome_type_idx'),
        ),
    ]
