# Generated by Django 4.2.12 on 2026-06-10 11:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('leads', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lead',
            name='lead_status',
            field=models.CharField(choices=[('NEW', 'New'), ('ASSIGNED', 'Assigned'), ('IN_PROGRESS', 'In Progress'), ('CALLBACK', 'Callback'), ('INTERESTED', 'Interested'), ('DOCUMENTS_REQUESTED', 'Documents Requested'), ('DOCUMENTS_RECEIVED', 'Documents Received'), ('BANK_LOGIN', 'Bank Login'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected'), ('DISBURSED', 'Disbursed')], db_index=True, default='NEW', help_text='Current status of the lead in the pipeline', max_length=20, verbose_name='Lead Status'),
        ),
        migrations.CreateModel(
            name='LeadStatusLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('old_status', models.CharField(blank=True, max_length=20, verbose_name='Old Status')),
                ('new_status', models.CharField(max_length=20, verbose_name='New Status')),
                ('notes', models.TextField(blank=True, help_text='Reason or context for the status change', verbose_name='Notes')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('changed_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lead_status_changes', to=settings.AUTH_USER_MODEL, verbose_name='Changed By')),
                ('lead', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='status_logs', to='leads.lead', verbose_name='Lead')),
            ],
            options={
                'verbose_name': 'Lead Status Log',
                'verbose_name_plural': 'Lead Status Logs',
                'db_table': 'leads_status_log',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['lead', 'created_at'], name='lslog_lead_date_idx'), models.Index(fields=['new_status'], name='lslog_new_status_idx')],
            },
        ),
        migrations.CreateModel(
            name='LeadNote',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('note_type', models.CharField(choices=[('GENERAL', 'General'), ('CALL', 'Call Notes'), ('MEETING', 'Meeting Notes'), ('DOCUMENT', 'Document Note'), ('FOLLOW_UP', 'Follow-up Note'), ('SYSTEM', 'System Generated')], default='GENERAL', max_length=20, verbose_name='Note Type')),
                ('content', models.TextField(help_text='Note content/description', verbose_name='Content')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lead_notes', to=settings.AUTH_USER_MODEL, verbose_name='Created By')),
                ('lead', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lead_notes', to='leads.lead', verbose_name='Lead')),
            ],
            options={
                'verbose_name': 'Lead Note',
                'verbose_name_plural': 'Lead Notes',
                'db_table': 'leads_lead_note',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['lead', 'created_at'], name='lnote_lead_date_idx'), models.Index(fields=['note_type'], name='lnote_type_idx')],
            },
        ),
        migrations.CreateModel(
            name='FollowUp',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('followup_type', models.CharField(choices=[('CALL', 'Call'), ('EMAIL', 'Email'), ('MEETING', 'Meeting'), ('SITE_VISIT', 'Site Visit'), ('DOCUMENT_FOLLOWUP', 'Document Follow-up'), ('OTHER', 'Other')], default='CALL', max_length=20, verbose_name='Follow-up Type')),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('COMPLETED', 'Completed'), ('CANCELLED', 'Cancelled'), ('RESCHEDULED', 'Rescheduled')], db_index=True, default='PENDING', max_length=20, verbose_name='Status')),
                ('scheduled_at', models.DateTimeField(help_text='When the follow-up is scheduled', verbose_name='Scheduled At')),
                ('completed_at', models.DateTimeField(blank=True, null=True, verbose_name='Completed At')),
                ('notes', models.TextField(blank=True, help_text='Notes about the follow-up', verbose_name='Notes')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('assigned_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lead_followups_assigned', to=settings.AUTH_USER_MODEL, verbose_name='Assigned To')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lead_followups_created', to=settings.AUTH_USER_MODEL, verbose_name='Created By')),
                ('lead', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lead_followups', to='leads.lead', verbose_name='Lead')),
            ],
            options={
                'verbose_name': 'Follow-up',
                'verbose_name_plural': 'Follow-ups',
                'db_table': 'leads_follow_up',
                'ordering': ['-scheduled_at'],
                'indexes': [models.Index(fields=['lead', 'status'], name='lfup_lead_status_idx'), models.Index(fields=['assigned_to', 'status'], name='lfup_user_status_idx'), models.Index(fields=['scheduled_at'], name='lfup_scheduled_idx')],
            },
        ),
    ]
