# Generated by Django 6.0.6 on 2026-06-10 12:32

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0002_alter_lead_lead_status_leadstatuslog_leadnote_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AssignmentRule',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(help_text='Human-readable name for this rule', max_length=200, verbose_name='Rule Name')),
                ('max_active_leads', models.IntegerField(default=50, help_text='Maximum active leads per assigned caller', verbose_name='Max Active Leads')),
                ('is_active', models.BooleanField(db_index=True, default=True, verbose_name='Is Active')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
            ],
            options={
                'verbose_name': 'Assignment Rule',
                'verbose_name_plural': 'Assignment Rules',
                'db_table': 'leads_assignment_rule',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='RoundRobinCounter',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('current_index', models.IntegerField(default=0, help_text='Current position in the rotation', verbose_name='Current Index')),
                ('assigned_count', models.IntegerField(default=0, help_text='Number of leads assigned in this cycle', verbose_name='Assigned Count')),
                ('last_assigned_at', models.DateTimeField(blank=True, null=True, verbose_name='Last Assigned At')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
            ],
            options={
                'verbose_name': 'Round Robin Counter',
                'verbose_name_plural': 'Round Robin Counters',
                'db_table': 'leads_round_robin_counter',
                'ordering': ['current_index'],
            },
        ),
        migrations.AddField(
            model_name='leadassignment',
            name='assignment_type',
            field=models.CharField(choices=[('MANUAL', 'Manual'), ('BULK', 'Bulk'), ('AUTO_ROUND_ROBIN', 'Auto Round Robin'), ('REASSIGNMENT', 'Reassignment')], db_index=True, default='MANUAL', help_text='How this assignment was made', max_length=20, verbose_name='Assignment Type'),
        ),
        migrations.AddIndex(
            model_name='leadassignment',
            index=models.Index(fields=['assignment_type'], name='assign_type_idx'),
        ),
        migrations.AddField(
            model_name='assignmentrule',
            name='campaign',
            field=models.ForeignKey(blank=True, help_text='Optional: scope rule to a specific campaign', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assignment_rules', to='leads.campaign', verbose_name='Campaign'),
        ),
        migrations.AddField(
            model_name='assignmentrule',
            name='team_lead',
            field=models.ForeignKey(help_text='Team lead who manages this rule', on_delete=django.db.models.deletion.CASCADE, related_name='assignment_rules', to=settings.AUTH_USER_MODEL, verbose_name='Team Lead'),
        ),
        migrations.AddField(
            model_name='roundrobincounter',
            name='caller',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='round_robin_entries', to=settings.AUTH_USER_MODEL, verbose_name='Caller'),
        ),
        migrations.AddField(
            model_name='roundrobincounter',
            name='rule',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='round_robin_counters', to='leads.assignmentrule', verbose_name='Rule'),
        ),
        migrations.AddIndex(
            model_name='assignmentrule',
            index=models.Index(fields=['team_lead', 'is_active'], name='assign_rule_lead_active_idx'),
        ),
        migrations.AddIndex(
            model_name='assignmentrule',
            index=models.Index(fields=['campaign'], name='assign_rule_campaign_idx'),
        ),
        migrations.AddIndex(
            model_name='roundrobincounter',
            index=models.Index(fields=['rule', 'current_index'], name='rr_rule_idx_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='roundrobincounter',
            unique_together={('rule', 'caller')},
        ),
    ]
