# Generated by Django 4.2.12 on 2026-06-10 13:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('leads', '0003_assignmentrule_roundrobincounter_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='LeadCall',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('call_type', models.CharField(choices=[('INBOUND', 'Inbound'), ('OUTBOUND', 'Outbound'), ('MISSED', 'Missed'), ('TRANSFERRED', 'Transferred')], db_index=True, default='OUTBOUND', max_length=20, verbose_name='Call Type')),
                ('call_status', models.CharField(choices=[('COMPLETED', 'Completed'), ('NO_ANSWER', 'No Answer'), ('BUSY', 'Busy'), ('FAILED', 'Failed'), ('CALLBACK', 'Callback Requested')], default='COMPLETED', max_length=20, verbose_name='Call Status')),
                ('duration_seconds', models.IntegerField(default=0, help_text='Call duration in seconds', verbose_name='Duration (seconds)')),
                ('notes', models.TextField(blank=True, help_text='Notes about the call conversation', verbose_name='Call Notes')),
                ('recording_url', models.URLField(blank=True, help_text='URL to call recording if available', verbose_name='Recording URL')),
                ('call_time', models.DateTimeField(db_index=True, help_text='When the call took place', verbose_name='Call Time')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('caller', models.ForeignKey(help_text='User who made/received the call', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lead_calls_made', to=settings.AUTH_USER_MODEL, verbose_name='Caller')),
                ('lead', models.ForeignKey(help_text='Associated lead', on_delete=django.db.models.deletion.CASCADE, related_name='calls', to='leads.lead', verbose_name='Lead')),
            ],
            options={
                'verbose_name': 'Lead Call',
                'verbose_name_plural': 'Lead Calls',
                'db_table': 'leads_lead_call',
                'ordering': ['-call_time'],
                'indexes': [models.Index(fields=['lead', 'call_time'], name='lcall_lead_time_idx'), models.Index(fields=['caller'], name='lcall_caller_idx'), models.Index(fields=['call_type'], name='lcall_type_idx')],
            },
        ),
    ]
