# Generated by Django 6.0.6 on 2026-06-10 07:16

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('leads', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Activity',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('activity_type', models.CharField(choices=[('CALL', 'Phone Call'), ('EMAIL', 'Email'), ('SMS', 'SMS'), ('SITE_VISIT', 'Site Visit'), ('DOCUMENT_SUBMISSION', 'Document Submission'), ('FEEDBACK', 'Feedback Collection')], db_index=True, help_text='Type of activity/follow-up', max_length=20, verbose_name='Activity Type')),
                ('status', models.CharField(choices=[('SCHEDULED', 'Scheduled'), ('IN_PROGRESS', 'In Progress'), ('COMPLETED', 'Completed'), ('CANCELLED', 'Cancelled'), ('PENDING', 'Pending')], db_index=True, default='SCHEDULED', help_text='Current status of the activity', max_length=20, verbose_name='Status')),
                ('scheduled_date', models.DateTimeField(db_index=True, help_text='When the activity is scheduled', verbose_name='Scheduled Date')),
                ('completed_date', models.DateTimeField(blank=True, help_text='When the activity was completed', null=True, verbose_name='Completed Date')),
                ('completion_notes', models.TextField(blank=True, help_text='Outcome/details of the completed activity', verbose_name='Completion Notes')),
                ('duration_minutes', models.IntegerField(blank=True, help_text='Duration of the activity in minutes', null=True, verbose_name='Duration (Minutes)')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('assigned_to', models.ForeignKey(blank=True, help_text='User responsible for this activity', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='activities', to=settings.AUTH_USER_MODEL, verbose_name='Assigned To')),
                ('created_by', models.ForeignKey(help_text='User who created the activity', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='activities_created', to=settings.AUTH_USER_MODEL, verbose_name='Created By')),
                ('lead', models.ForeignKey(help_text='Associated lead', on_delete=django.db.models.deletion.CASCADE, related_name='activities', to='leads.lead', verbose_name='Lead')),
            ],
            options={
                'verbose_name': 'Activity',
                'verbose_name_plural': 'Activities',
                'db_table': 'activities_activity',
                'ordering': ['-scheduled_date'],
                'indexes': [models.Index(fields=['lead', 'status'], name='activity_lead_status_idx'), models.Index(fields=['assigned_to', 'status'], name='activity_user_status_idx'), models.Index(fields=['assigned_to', 'scheduled_date'], name='activity_user_date_idx'), models.Index(fields=['status'], name='activity_status_idx'), models.Index(fields=['activity_type'], name='activity_type_idx'), models.Index(fields=['scheduled_date'], name='activity_scheduled_idx')],
            },
        ),
        migrations.CreateModel(
            name='FollowUp',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('priority', models.CharField(choices=[('HIGH', 'High'), ('MEDIUM', 'Medium'), ('LOW', 'Low')], db_index=True, default='MEDIUM', help_text='Priority level of the follow-up', max_length=10, verbose_name='Priority')),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('SCHEDULED', 'Scheduled'), ('COMPLETED', 'Completed'), ('CANCELLED', 'Cancelled')], db_index=True, default='PENDING', help_text='Current status of the follow-up', max_length=20, verbose_name='Status')),
                ('scheduled_for', models.DateField(db_index=True, help_text='Scheduled date for the follow-up', verbose_name='Scheduled For')),
                ('description', models.TextField(blank=True, help_text='Details about what needs to be followed up', verbose_name='Description')),
                ('completed_at', models.DateTimeField(blank=True, help_text='When the follow-up was completed', null=True, verbose_name='Completed At')),
                ('completion_remarks', models.TextField(blank=True, help_text='Remarks on completion', verbose_name='Completion Remarks')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('assigned_to', models.ForeignKey(blank=True, help_text='User responsible for follow-up', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='followups', to=settings.AUTH_USER_MODEL, verbose_name='Assigned To')),
                ('created_by', models.ForeignKey(help_text='User who created the follow-up', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='followups_created', to=settings.AUTH_USER_MODEL, verbose_name='Created By')),
                ('lead', models.ForeignKey(help_text='Associated lead', on_delete=django.db.models.deletion.CASCADE, related_name='followups', to='leads.lead', verbose_name='Lead')),
            ],
            options={
                'verbose_name': 'Follow-up',
                'verbose_name_plural': 'Follow-ups',
                'db_table': 'activities_followup',
                'ordering': ['scheduled_for'],
                'indexes': [models.Index(fields=['lead', 'status'], name='followup_lead_status_idx'), models.Index(fields=['assigned_to', 'status'], name='followup_user_status_idx'), models.Index(fields=['assigned_to', 'scheduled_for'], name='followup_user_date_idx'), models.Index(fields=['status'], name='followup_status_idx'), models.Index(fields=['priority'], name='followup_priority_idx')],
            },
        ),
        migrations.CreateModel(
            name='Note',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('content', models.TextField(help_text='Note content', verbose_name='Content')),
                ('note_type', models.CharField(choices=[('INTERNAL', 'Internal'), ('CUSTOMER_FACING', 'Customer Facing')], db_index=True, default='INTERNAL', help_text='Type of note', max_length=20, verbose_name='Note Type')),
                ('is_internal', models.BooleanField(db_index=True, default=True, help_text='Whether this note is for internal use only', verbose_name='Is Internal')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('created_by', models.ForeignKey(help_text='User who created the note', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='notes_created', to=settings.AUTH_USER_MODEL, verbose_name='Created By')),
                ('lead', models.ForeignKey(help_text='Associated lead', on_delete=django.db.models.deletion.CASCADE, related_name='notes', to='leads.lead', verbose_name='Lead')),
            ],
            options={
                'verbose_name': 'Note',
                'verbose_name_plural': 'Notes',
                'db_table': 'activities_note',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['lead'], name='note_lead_idx'), models.Index(fields=['note_type'], name='note_type_idx'), models.Index(fields=['created_at'], name='note_created_idx')],
            },
        ),
    ]
