# Generated by Django 6.0.6 on 2026-06-10 07:16

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('leads', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ExcelImport',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('file_path', models.CharField(help_text='Path to the uploaded Excel file', max_length=500, verbose_name='File Path')),
                ('file_name', models.CharField(blank=True, help_text='Original file name', max_length=255, verbose_name='File Name')),
                ('file_size', models.IntegerField(blank=True, help_text='File size in bytes', null=True, verbose_name='File Size')),
                ('imported_at', models.DateTimeField(auto_now_add=True, help_text='When file was uploaded', verbose_name='Imported At')),
                ('processed_at', models.DateTimeField(blank=True, help_text='When file was processed', null=True, verbose_name='Processed At')),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('PROCESSING', 'Processing'), ('COMPLETED', 'Completed'), ('FAILED', 'Failed')], db_index=True, default='PENDING', help_text='Current import status', max_length=20, verbose_name='Status')),
                ('total_rows', models.IntegerField(default=0, help_text='Total rows in the Excel file', verbose_name='Total Rows')),
                ('successful_rows', models.IntegerField(default=0, help_text='Number of successfully imported rows', verbose_name='Successful Rows')),
                ('failed_rows', models.IntegerField(default=0, help_text='Number of rows that failed', verbose_name='Failed Rows')),
                ('error_log', models.TextField(blank=True, help_text='Detailed error messages in JSON format. Use JSONField with PostgreSQL.', null=True, verbose_name='Error Log')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('batch', models.OneToOneField(help_text='Associated batch', on_delete=django.db.models.deletion.CASCADE, related_name='excel_import', to='leads.batch', verbose_name='Batch')),
                ('created_by', models.ForeignKey(help_text='User who initiated the import', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='excel_imports', to=settings.AUTH_USER_MODEL, verbose_name='Created By')),
            ],
            options={
                'verbose_name': 'Excel Import',
                'verbose_name_plural': 'Excel Imports',
                'db_table': 'excel_import',
                'ordering': ['-imported_at'],
            },
        ),
        migrations.CreateModel(
            name='ExcelImportLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('row_number', models.IntegerField(help_text='Row number in the Excel file', verbose_name='Row Number')),
                ('status', models.CharField(choices=[('SUCCESS', 'Success'), ('FAILED', 'Failed'), ('SKIPPED', 'Skipped')], db_index=True, help_text='Import status for this row', max_length=10, verbose_name='Status')),
                ('error_message', models.TextField(blank=True, help_text='Error details if import failed', verbose_name='Error Message')),
                ('raw_data', models.TextField(blank=True, help_text='Raw data from the Excel row (JSON format). Use JSONField with PostgreSQL.', null=True, verbose_name='Raw Data')),
                ('created_lead_id', models.CharField(blank=True, help_text='ID of created lead (if successful)', max_length=100, verbose_name='Created Lead ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('excel_import', models.ForeignKey(help_text='Associated Excel import session', on_delete=django.db.models.deletion.CASCADE, related_name='logs', to='excel.excelimport', verbose_name='Excel Import')),
            ],
            options={
                'verbose_name': 'Excel Import Log',
                'verbose_name_plural': 'Excel Import Logs',
                'db_table': 'excel_import_log',
                'ordering': ['row_number'],
            },
        ),
        migrations.AddIndex(
            model_name='excelimport',
            index=models.Index(fields=['status'], name='excel_status_idx'),
        ),
        migrations.AddIndex(
            model_name='excelimport',
            index=models.Index(fields=['created_by'], name='excel_created_by_idx'),
        ),
        migrations.AddIndex(
            model_name='excelimportlog',
            index=models.Index(fields=['excel_import', 'status'], name='excel_log_import_status_idx'),
        ),
        migrations.AddIndex(
            model_name='excelimportlog',
            index=models.Index(fields=['row_number'], name='excel_log_row_idx'),
        ),
    ]
