# Generated by Django 6.0.6 on 2026-06-10 07:16

import django.contrib.auth.models
import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, verbose_name='username')),
                ('email', models.EmailField(db_index=True, help_text='Email must be unique within the system.', max_length=254, unique=True, verbose_name='email address')),
                ('phone', models.CharField(blank=True, db_index=True, max_length=15, null=True, verbose_name='Phone Number')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('last_activity_at', models.DateTimeField(blank=True, help_text='Track when user last performed an action.', null=True, verbose_name='Last Activity At')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'User',
                'verbose_name_plural': 'Users',
                'db_table': 'auth_user_extended',
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Permission',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('code', models.CharField(db_index=True, help_text='Unique identifier for the permission (e.g., leads.add_lead)', max_length=100, unique=True, verbose_name='Permission Code')),
                ('name', models.CharField(help_text='Human-readable permission name', max_length=200, verbose_name='Permission Name')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('module', models.CharField(choices=[('LEADS', 'Leads'), ('ACTIVITIES', 'Activities'), ('REPORTS', 'Reports'), ('USERS', 'Users'), ('SETTINGS', 'Settings'), ('AUDIT', 'Audit'), ('IMPORTS', 'Imports')], db_index=True, max_length=20, verbose_name='Module')),
                ('is_active', models.BooleanField(db_index=True, default=True, verbose_name='Is Active')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
            ],
            options={
                'verbose_name': 'Permission',
                'verbose_name_plural': 'Permissions',
                'db_table': 'auth_permission_custom',
                'ordering': ['module', 'code'],
                'indexes': [models.Index(fields=['code'], name='permission_code_idx'), models.Index(fields=['module'], name='permission_module_idx')],
            },
        ),
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('role_code', models.CharField(choices=[('SUPER_ADMIN', 'Super Admin'), ('TEAM_LEAD', 'Team Lead'), ('CALLER', 'Caller'), ('DATA_ENTRY', 'Data Entry Operator')], db_index=True, max_length=20, unique=True, verbose_name='Role Code')),
                ('name', models.CharField(help_text='Human-readable role name', max_length=100, unique=True, verbose_name='Role Name')),
                ('description', models.TextField(blank=True, help_text='Detailed description of the role and its responsibilities', verbose_name='Description')),
                ('is_active', models.BooleanField(db_index=True, default=True, verbose_name='Is Active')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('permissions', models.ManyToManyField(blank=True, help_text='Select permissions associated with this role', related_name='roles', to='accounts.permission', verbose_name='Permissions')),
            ],
            options={
                'verbose_name': 'Role',
                'verbose_name_plural': 'Roles',
                'db_table': 'auth_role',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('department', models.CharField(blank=True, choices=[('SALES', 'Sales'), ('OPERATIONS', 'Operations'), ('SUPPORT', 'Support'), ('MANAGEMENT', 'Management'), ('FINANCE', 'Finance'), ('ADMIN', 'Administration')], max_length=20, verbose_name='Department')),
                ('phone', models.CharField(blank=True, db_index=True, max_length=15, verbose_name='Phone Number')),
                ('profile_image', models.ImageField(blank=True, null=True, upload_to='profile_images/', verbose_name='Profile Image')),
                ('bio', models.TextField(blank=True, max_length=500, verbose_name='Bio')),
                ('is_active', models.BooleanField(db_index=True, default=True, help_text='Inactive users cannot log in', verbose_name='Is Active')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('manager', models.ForeignKey(blank=True, help_text='Direct manager/supervisor', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='subordinates', to='accounts.userprofile', verbose_name='Manager')),
                ('role', models.ForeignKey(help_text="User's role in the system", on_delete=django.db.models.deletion.PROTECT, related_name='user_profiles', to='accounts.role', verbose_name='Role')),
                ('user', models.OneToOneField(help_text='Associated user account', on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
            options={
                'verbose_name': 'User Profile',
                'verbose_name_plural': 'User Profiles',
                'db_table': 'auth_user_profile',
            },
        ),
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['email'], name='user_email_idx'),
        ),
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['username'], name='user_username_idx'),
        ),
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['is_active'], name='user_is_active_idx'),
        ),
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['-created_at'], name='user_created_at_idx'),
        ),
        migrations.AddIndex(
            model_name='role',
            index=models.Index(fields=['role_code'], name='role_code_idx'),
        ),
        migrations.AddIndex(
            model_name='role',
            index=models.Index(fields=['is_active'], name='role_is_active_idx'),
        ),
        migrations.AddIndex(
            model_name='userprofile',
            index=models.Index(fields=['role'], name='userprofile_role_idx'),
        ),
        migrations.AddIndex(
            model_name='userprofile',
            index=models.Index(fields=['manager'], name='userprofile_manager_idx'),
        ),
        migrations.AddIndex(
            model_name='userprofile',
            index=models.Index(fields=['is_active'], name='userprofile_is_active_idx'),
        ),
    ]
