# Generated by Django 6.0.6 on 2026-06-12 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='role',
            name='role_code',
            field=models.CharField(choices=[('SUPER_ADMIN', 'Super Admin'), ('MANAGER', 'Manager'), ('TEAM_LEAD', 'Team Lead'), ('ARO', 'ARO (Agent)'), ('CALLER', 'Caller'), ('DATA_ENTRY', 'Data Entry Operator')], db_index=True, max_length=20, unique=True, verbose_name='Role Code'),
        ),
    ]
