# Generated by Django 4.2.12 on 2026-06-13 11:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_role_role_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='role',
            field=models.ForeignKey(blank=True, help_text="User's role in the system", null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='user_profiles', to='accounts.role', verbose_name='Role'),
        ),
    ]
