# Generated by Django 4.2.12 on 2026-06-12 09:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('leads', '0004_add_lead_call_model'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UploadBatch',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('batch_code', models.CharField(db_index=True, help_text='Auto-generated batch code (e.g. HDFC-JUNE-001)', max_length=50, unique=True, verbose_name='Batch Code')),
                ('upload_type', models.CharField(choices=[('EXCEL', 'Excel'), ('PDF', 'PDF'), ('IMAGE', 'Image')], db_index=True, help_text='Format of the uploaded file', max_length=10, verbose_name='Upload Type')),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('PENDING', 'Pending'), ('PROCESSING', 'Processing'), ('COMPLETED', 'Completed'), ('PARTIAL', 'Partially Completed'), ('FAILED', 'Failed'), ('CANCELLED', 'Cancelled')], db_index=True, default='DRAFT', max_length=20, verbose_name='Batch Status')),
                ('original_filename', models.CharField(blank=True, max_length=500, verbose_name='Original Filename')),
                ('file_path', models.CharField(blank=True, max_length=1000, verbose_name='File Path')),
                ('file_size', models.BigIntegerField(blank=True, help_text='File size in bytes', null=True, verbose_name='File Size')),
                ('total_records', models.IntegerField(default=0, help_text='Number of records in the uploaded file', verbose_name='Total Records')),
                ('processed_records', models.IntegerField(default=0, help_text='Number of records that have been processed', verbose_name='Processed Records')),
                ('failed_records', models.IntegerField(default=0, help_text='Number of records that failed processing', verbose_name='Failed Records')),
                ('upload_date', models.DateTimeField(auto_now_add=True, verbose_name='Upload Date')),
                ('processed_at', models.DateTimeField(blank=True, null=True, verbose_name='Processed At')),
                ('notes', models.TextField(blank=True, help_text='Internal notes about this upload', verbose_name='Notes')),
                ('error_log', models.TextField(blank=True, verbose_name='Error Log')),
                ('metadata', models.TextField(blank=True, help_text='Additional metadata as JSON', verbose_name='Metadata')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('bank_source', models.ForeignKey(help_text='Bank or financial institution this data belongs to', on_delete=django.db.models.deletion.PROTECT, related_name='upload_batches', to='leads.banksource', verbose_name='Source Name')),
                ('uploaded_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='upload_batches', to=settings.AUTH_USER_MODEL, verbose_name='Uploaded By')),
            ],
            options={
                'verbose_name': 'Upload Batch',
                'verbose_name_plural': 'Upload Batches',
                'db_table': 'documents_upload_batch',
                'ordering': ['-upload_date'],
            },
        ),
        migrations.CreateModel(
            name='WorkItem',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('item_identifier', models.CharField(blank=True, help_text='Row number, page number, or image index within the batch', max_length=100, verbose_name='Item Identifier')),
                ('sequence', models.IntegerField(default=0, help_text='Display order within the batch', verbose_name='Sequence')),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('ASSIGNED', 'Assigned'), ('IN_PROGRESS', 'In Progress'), ('COMPLETED', 'Completed'), ('REVERTED', 'Reverted'), ('FAILED', 'Failed'), ('SKIPPED', 'Skipped')], db_index=True, default='PENDING', max_length=20, verbose_name='Work Item Status')),
                ('priority', models.CharField(choices=[('HIGH', 'High'), ('MEDIUM', 'Medium'), ('LOW', 'Low')], default='MEDIUM', max_length=10, verbose_name='Priority')),
                ('assigned_at', models.DateTimeField(blank=True, null=True, verbose_name='Assigned At')),
                ('extracted_data', models.TextField(blank=True, help_text='Raw extracted data from the source document as JSON', verbose_name='Extracted Data')),
                ('result_data', models.TextField(blank=True, help_text='Processed/corrected data after review as JSON', verbose_name='Result Data')),
                ('internal_notes', models.TextField(blank=True, verbose_name='Internal Notes')),
                ('error_message', models.TextField(blank=True, verbose_name='Error Message')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('completed_at', models.DateTimeField(blank=True, null=True, verbose_name='Completed At')),
                ('assigned_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_work_items', to=settings.AUTH_USER_MODEL, verbose_name='Assigned To')),
                ('batch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='work_items', to='documents.uploadbatch', verbose_name='Upload Batch')),
                ('lead', models.ForeignKey(blank=True, help_text='The lead record created from this work item', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='source_work_items', to='leads.lead', verbose_name='Linked Lead')),
            ],
            options={
                'verbose_name': 'Work Item',
                'verbose_name_plural': 'Work Items',
                'db_table': 'documents_work_item',
                'ordering': ['batch', 'sequence'],
            },
        ),
        migrations.CreateModel(
            name='WorkAssignment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('assigned_at', models.DateTimeField(auto_now_add=True, verbose_name='Assigned At')),
                ('unassigned_at', models.DateTimeField(blank=True, null=True, verbose_name='Unassigned At')),
                ('notes', models.TextField(blank=True, help_text='Reason for this assignment', verbose_name='Assignment Notes')),
                ('assigned_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='work_assignments_made', to=settings.AUTH_USER_MODEL, verbose_name='Assigned By')),
                ('assigned_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='work_assignments', to=settings.AUTH_USER_MODEL, verbose_name='Assigned To')),
                ('work_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to='documents.workitem', verbose_name='Work Item')),
            ],
            options={
                'verbose_name': 'Work Assignment',
                'verbose_name_plural': 'Work Assignments',
                'db_table': 'documents_work_assignment',
                'ordering': ['-assigned_at'],
            },
        ),
        migrations.CreateModel(
            name='WorkTimeline',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('action', models.CharField(choices=[('CREATED', 'Item Created'), ('ASSIGNED', 'Assigned'), ('UNASSIGNED', 'Unassigned'), ('REASSIGNED', 'Reassigned'), ('STATUS_CHANGED', 'Status Changed'), ('NOTE_ADDED', 'Note Added'), ('DATA_UPDATED', 'Data Updated'), ('REVERTED', 'Reverted'), ('COMPLETED', 'Completed'), ('REOPENED', 'Reopened'), ('ERROR', 'Error'), ('COMMENT', 'Comment')], db_index=True, max_length=20, verbose_name='Action')),
                ('description', models.TextField(blank=True, help_text='Human-readable description of what happened', verbose_name='Description')),
                ('from_status', models.CharField(blank=True, max_length=20, verbose_name='From Status')),
                ('to_status', models.CharField(blank=True, max_length=20, verbose_name='To Status')),
                ('metadata', models.TextField(blank=True, help_text='Additional context as JSON', verbose_name='Metadata')),
                ('is_system_generated', models.BooleanField(default=False, verbose_name='System Generated')),
                ('timestamp', models.DateTimeField(db_index=True, help_text='When this activity occurred', verbose_name='Timestamp')),
                ('performed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='work_timeline_entries', to=settings.AUTH_USER_MODEL, verbose_name='Performed By')),
                ('work_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='timeline_entries', to='documents.workitem', verbose_name='Work Item')),
            ],
            options={
                'verbose_name': 'Work Timeline Entry',
                'verbose_name_plural': 'Work Timeline Entries',
                'db_table': 'documents_work_timeline',
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['work_item', 'timestamp'], name='doc_tl_wi_ts_idx'), models.Index(fields=['action'], name='doc_tl_action_idx'), models.Index(fields=['performed_by'], name='doc_tl_user_idx')],
            },
        ),
        migrations.CreateModel(
            name='WorkRevert',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('reason', models.CharField(choices=[('DUPLICATE', 'Duplicate Entry'), ('INCORRECT_DATA', 'Incorrect Data'), ('USER_ERROR', 'User Error'), ('SYSTEM_ERROR', 'System Error'), ('CLIENT_REQUEST', 'Client Request'), ('QUALITY_REJECT', 'Quality Reject'), ('OTHER', 'Other')], default='OTHER', max_length=30, verbose_name='Revert Reason')),
                ('reason_details', models.TextField(blank=True, verbose_name='Reason Details')),
                ('previous_status', models.CharField(blank=True, help_text='Status before the revert', max_length=20, verbose_name='Previous Status')),
                ('restored_status', models.CharField(blank=True, help_text='Status restored to after the revert', max_length=20, verbose_name='Restored Status')),
                ('changed_fields', models.TextField(blank=True, help_text='JSON object describing which fields were reverted and their old/new values', verbose_name='Changed Fields')),
                ('reverted_at', models.DateTimeField(auto_now_add=True, verbose_name='Reverted At')),
                ('reverted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='work_reverts', to=settings.AUTH_USER_MODEL, verbose_name='Reverted By')),
                ('work_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reverts', to='documents.workitem', verbose_name='Work Item')),
            ],
            options={
                'verbose_name': 'Work Revert',
                'verbose_name_plural': 'Work Reverts',
                'db_table': 'documents_work_revert',
                'ordering': ['-reverted_at'],
                'indexes': [models.Index(fields=['work_item'], name='doc_revert_wi_idx'), models.Index(fields=['reverted_by'], name='doc_revert_user_idx')],
            },
        ),
        migrations.CreateModel(
            name='WorkNote',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('note_type', models.CharField(choices=[('INTERNAL', 'Internal'), ('CUSTOMER_FACING', 'Customer Facing'), ('REVIEW', 'Review Note'), ('CORRECTION', 'Correction')], default='INTERNAL', max_length=20, verbose_name='Note Type')),
                ('content', models.TextField(verbose_name='Note Content')),
                ('is_internal', models.BooleanField(default=True, help_text='Internal notes are not visible to customers', verbose_name='Is Internal')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='work_notes', to=settings.AUTH_USER_MODEL, verbose_name='Created By')),
                ('work_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notes', to='documents.workitem', verbose_name='Work Item')),
            ],
            options={
                'verbose_name': 'Work Note',
                'verbose_name_plural': 'Work Notes',
                'db_table': 'documents_work_note',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['work_item'], name='doc_note_wi_idx'), models.Index(fields=['created_by'], name='doc_note_user_idx')],
            },
        ),
        migrations.AddIndex(
            model_name='workitem',
            index=models.Index(fields=['batch', 'status'], name='doc_wi_batch_status_idx'),
        ),
        migrations.AddIndex(
            model_name='workitem',
            index=models.Index(fields=['status'], name='doc_wi_status_idx'),
        ),
        migrations.AddIndex(
            model_name='workitem',
            index=models.Index(fields=['assigned_to'], name='doc_wi_assigned_idx'),
        ),
        migrations.AddIndex(
            model_name='workitem',
            index=models.Index(fields=['batch', 'sequence'], name='doc_wi_batch_seq_idx'),
        ),
        migrations.AddIndex(
            model_name='workassignment',
            index=models.Index(fields=['work_item'], name='doc_assign_wi_idx'),
        ),
        migrations.AddIndex(
            model_name='workassignment',
            index=models.Index(fields=['assigned_to'], name='doc_assign_user_idx'),
        ),
        migrations.AddIndex(
            model_name='uploadbatch',
            index=models.Index(fields=['batch_code'], name='doc_batch_code_idx'),
        ),
        migrations.AddIndex(
            model_name='uploadbatch',
            index=models.Index(fields=['bank_source'], name='doc_batch_source_idx'),
        ),
        migrations.AddIndex(
            model_name='uploadbatch',
            index=models.Index(fields=['upload_type'], name='doc_batch_type_idx'),
        ),
        migrations.AddIndex(
            model_name='uploadbatch',
            index=models.Index(fields=['status'], name='doc_batch_status_idx'),
        ),
        migrations.AddIndex(
            model_name='uploadbatch',
            index=models.Index(fields=['uploaded_by'], name='doc_batch_uploader_idx'),
        ),
        migrations.AddIndex(
            model_name='uploadbatch',
            index=models.Index(fields=['upload_date'], name='doc_batch_date_idx'),
        ),
    ]
