# Generated by Django 4.2.12 on 2026-06-12 09:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='workitem',
            name='page_number',
            field=models.IntegerField(blank=True, help_text='Page number in the source PDF (1-indexed)', null=True, verbose_name='Page Number'),
        ),
        migrations.AddField(
            model_name='workitem',
            name='page_preview',
            field=models.CharField(blank=True, help_text='Path to the rendered page preview image', max_length=1000, verbose_name='Page Preview'),
        ),
        migrations.AddField(
            model_name='workitem',
            name='page_thumbnail',
            field=models.CharField(blank=True, help_text='Path to the page thumbnail image', max_length=1000, verbose_name='Page Thumbnail'),
        ),
    ]
