# Generated by Django 4.2.12 on 2026-06-12 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0002_workitem_page_number_workitem_page_preview_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='workitem',
            name='image_original',
            field=models.CharField(blank=True, help_text='Path to the original uploaded image', max_length=1000, verbose_name='Original Image'),
        ),
        migrations.AddField(
            model_name='workitem',
            name='image_preview',
            field=models.CharField(blank=True, help_text='Path to the resized preview image', max_length=1000, verbose_name='Image Preview'),
        ),
        migrations.AddField(
            model_name='workitem',
            name='image_thumbnail',
            field=models.CharField(blank=True, help_text='Path to the image thumbnail', max_length=1000, verbose_name='Image Thumbnail'),
        ),
    ]
