# Generated by Django 6.0.6 on 2026-06-12 10:18

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0003_workitem_image_original_workitem_image_preview_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='workitem',
            name='status',
            field=models.CharField(choices=[('NEW', 'New'), ('ASSIGNED', 'Assigned'), ('IN_PROGRESS', 'In Progress'), ('PENDING', 'Pending'), ('NEED_CLARIFICATION', 'Need Clarification'), ('COMPLETED', 'Completed'), ('REJECTED', 'Rejected'), ('CLOSED', 'Closed')], db_index=True, default='NEW', max_length=20, verbose_name='Work Item Status'),
        ),
        migrations.AlterField(
            model_name='worktimeline',
            name='action',
            field=models.CharField(choices=[('CREATED', 'Item Created'), ('ASSIGNED', 'Assigned'), ('UNASSIGNED', 'Unassigned'), ('REASSIGNED', 'Reassigned'), ('STATUS_CHANGED', 'Status Changed'), ('NOTE_ADDED', 'Note Added'), ('DATA_UPDATED', 'Data Updated'), ('REVERTED', 'Reverted'), ('COMPLETED', 'Completed'), ('REOPENED', 'Reopened'), ('REJECTED', 'Rejected'), ('CLOSED', 'Closed'), ('NEED_CLARIFICATION', 'Need Clarification'), ('PENDING', 'Pending'), ('ERROR', 'Error'), ('COMMENT', 'Comment')], db_index=True, max_length=20, verbose_name='Action'),
        ),
        migrations.CreateModel(
            name='WorkItemStatus',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('NEW', 'New'), ('ASSIGNED', 'Assigned'), ('IN_PROGRESS', 'In Progress'), ('PENDING', 'Pending'), ('NEED_CLARIFICATION', 'Need Clarification'), ('COMPLETED', 'Completed'), ('REJECTED', 'Rejected'), ('CLOSED', 'Closed')], max_length=20, verbose_name='Status')),
                ('changed_at', models.DateTimeField(db_index=True, verbose_name='Changed At')),
                ('from_status', models.CharField(blank=True, help_text='Previous status (blank for initial)', max_length=20, verbose_name='From Status')),
                ('notes', models.TextField(blank=True, help_text='Reason or context for this status change', verbose_name='Notes')),
                ('is_system', models.BooleanField(default=False, help_text='True if this change was made automatically by the system', verbose_name='System Change')),
                ('changed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='work_item_status_changes', to=settings.AUTH_USER_MODEL, verbose_name='Changed By')),
                ('work_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='status_history', to='documents.workitem', verbose_name='Work Item')),
            ],
            options={
                'verbose_name': 'Work Item Status Entry',
                'verbose_name_plural': 'Work Item Status History',
                'db_table': 'documents_work_item_status',
                'ordering': ['-changed_at'],
                'indexes': [models.Index(fields=['work_item', 'changed_at'], name='doc_wis_wi_ts_idx'), models.Index(fields=['status'], name='doc_wis_status_idx'), models.Index(fields=['changed_by'], name='doc_wis_user_idx')],
            },
        ),
    ]
