# Generated by Django 6.0.6 on 2026-06-12 10:26

import documents.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0004_alter_workitem_status_alter_worktimeline_action_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='workrevert',
            name='attachment',
            field=models.FileField(blank=True, help_text='Optional supporting file (image, PDF, document)', null=True, upload_to=documents.models.WORK_ITEM_FILE_PATH, verbose_name='Attachment'),
        ),
        migrations.AddField(
            model_name='workrevert',
            name='remarks',
            field=models.TextField(blank=True, help_text='Additional remarks about this revert', verbose_name='Remarks'),
        ),
        migrations.AlterField(
            model_name='workrevert',
            name='reason',
            field=models.CharField(choices=[('DUPLICATE', 'Duplicate Entry'), ('INCORRECT_DATA', 'Incorrect Data'), ('USER_ERROR', 'User Error'), ('SYSTEM_ERROR', 'System Error'), ('CLIENT_REQUEST', 'Client Request'), ('QUALITY_REJECT', 'Quality Reject'), ('DOCUMENT_INCOMPLETE', 'Document Incomplete'), ('NEED_BETTER_IMAGE', 'Need Better Image'), ('VERIFIED', 'Verified'), ('OTHER', 'Other')], default='OTHER', max_length=30, verbose_name='Revert Reason'),
        ),
    ]
