# Generated by Django 6.0.6 on 2026-06-12 10:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0005_workrevert_attachment_workrevert_remarks_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='worknote',
            options={'ordering': ['created_at'], 'verbose_name': 'Work Note', 'verbose_name_plural': 'Work Notes'},
        ),
        migrations.RemoveField(
            model_name='worknote',
            name='is_internal',
        ),
        migrations.RemoveField(
            model_name='worknote',
            name='note_type',
        ),
        migrations.RemoveField(
            model_name='worknote',
            name='updated_at',
        ),
        migrations.AlterField(
            model_name='worknote',
            name='content',
            field=models.TextField(verbose_name='Note Text'),
        ),
        migrations.AlterField(
            model_name='worknote',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Date'),
        ),
        migrations.AlterField(
            model_name='worknote',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='work_notes', to=settings.AUTH_USER_MODEL, verbose_name='Author'),
        ),
    ]
