# Generated by Django 6.0.6 on 2026-06-12 10:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0006_alter_worknote_options_remove_worknote_is_internal_and_more'),
        ('leads', '0004_add_lead_call_model'),
    ]

    operations = [
        migrations.AlterField(
            model_name='uploadbatch',
            name='bank_source',
            field=models.ForeignKey(blank=True, help_text='Bank or financial institution this data belongs to', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='upload_batches', to='leads.banksource', verbose_name='Source Name'),
        ),
    ]
