# Generated by Django 4.2.12 on 2026-06-13 06:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0007_alter_uploadbatch_bank_source'),
    ]

    operations = [
        migrations.AddField(
            model_name='worknote',
            name='is_feedback',
            field=models.BooleanField(default=False, help_text='Mark as feedback visible to managers and team leads', verbose_name='Feedback'),
        ),
    ]
