# Generated by Django 4.2.12 on 2026-06-13 06:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0008_worknote_feedback'),
    ]

    operations = [
        migrations.AlterField(
            model_name='worktimeline',
            name='action',
            field=models.CharField(choices=[('CREATED', 'Item Created'), ('ASSIGNED', 'Assigned'), ('UNASSIGNED', 'Unassigned'), ('REASSIGNED', 'Reassigned'), ('STATUS_CHANGED', 'Status Changed'), ('NOTE_ADDED', 'Note Added'), ('DATA_UPDATED', 'Data Updated'), ('REVERTED', 'Reverted'), ('COMPLETED', 'Completed'), ('REOPENED', 'Reopened'), ('REJECTED', 'Rejected'), ('CLOSED', 'Closed'), ('NEED_CLARIFICATION', 'Need Clarification'), ('PENDING', 'Pending'), ('ERROR', 'Error'), ('COMMENT', 'Comment'), ('FEEDBACK', 'Feedback')], db_index=True, max_length=20, verbose_name='Action'),
        ),
    ]
