# Generated by Django 6.0.6 on 2026-06-10 07:16

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('model_name', models.CharField(db_index=True, help_text='Name of the model affected (Lead, Activity, etc.)', max_length=100, verbose_name='Model Name')),
                ('record_id', models.CharField(db_index=True, help_text='ID of the record affected', max_length=100, verbose_name='Record ID')),
                ('action', models.CharField(choices=[('CREATE', 'Create'), ('UPDATE', 'Update'), ('DELETE', 'Delete'), ('VIEW', 'View'), ('EXPORT', 'Export'), ('LOGIN', 'Login'), ('LOGOUT', 'Logout'), ('ASSIGN', 'Assign'), ('BULK_ACTION', 'Bulk Action')], db_index=True, help_text='Type of action performed', max_length=20, verbose_name='Action')),
                ('old_values', models.TextField(blank=True, help_text='Previous values before change (JSON format). Use JSONField with PostgreSQL.', null=True, verbose_name='Old Values')),
                ('new_values', models.TextField(blank=True, help_text='New values after change (JSON format). Use JSONField with PostgreSQL.', null=True, verbose_name='New Values')),
                ('ip_address', models.GenericIPAddressField(blank=True, help_text='IP address of the user', null=True, verbose_name='IP Address')),
                ('user_agent', models.TextField(blank=True, help_text='Browser/client user agent string', verbose_name='User Agent')),
                ('description', models.TextField(blank=True, help_text='Human-readable description of the action', verbose_name='Description')),
                ('timestamp', models.DateTimeField(auto_now_add=True, db_index=True, help_text='When the action occurred', verbose_name='Timestamp')),
                ('user', models.ForeignKey(help_text='User who performed the action', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_logs', to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
            options={
                'verbose_name': 'Audit Log',
                'verbose_name_plural': 'Audit Logs',
                'db_table': 'audit_log',
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['user', 'timestamp'], name='audit_user_time_idx'), models.Index(fields=['model_name', 'record_id'], name='audit_model_record_idx'), models.Index(fields=['action'], name='audit_action_idx'), models.Index(fields=['timestamp'], name='audit_timestamp_idx')],
            },
        ),
        migrations.CreateModel(
            name='UserActionLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('action_type', models.CharField(choices=[('LOGIN', 'Login'), ('LOGOUT', 'Logout'), ('LEAD_VIEW', 'Lead View'), ('LEAD_EDIT', 'Lead Edit'), ('ACTIVITY_CREATE', 'Activity Create'), ('ACTIVITY_COMPLETE', 'Activity Complete'), ('REPORT_GENERATE', 'Report Generate'), ('IMPORT_START', 'Import Start'), ('IMPORT_COMPLETE', 'Import Complete')], db_index=True, help_text='Type of action performed', max_length=30, verbose_name='Action Type')),
                ('resource_type', models.CharField(blank=True, help_text='Type of resource affected (Lead, Activity, etc.)', max_length=50, verbose_name='Resource Type')),
                ('resource_id', models.CharField(blank=True, db_index=True, help_text='ID of the resource affected', max_length=100, verbose_name='Resource ID')),
                ('duration_seconds', models.IntegerField(blank=True, help_text='Time spent on the action', null=True, verbose_name='Duration (Seconds)')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True, verbose_name='IP Address')),
                ('status', models.CharField(default='SUCCESS', help_text='Success or failure status', max_length=20, verbose_name='Status')),
                ('details', models.TextField(blank=True, help_text='Additional details about the action (JSON format). Use JSONField with PostgreSQL.', null=True, verbose_name='Details')),
                ('timestamp', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Timestamp')),
                ('user', models.ForeignKey(help_text='User who performed the action', on_delete=django.db.models.deletion.CASCADE, related_name='user_actions', to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
            options={
                'verbose_name': 'User Action Log',
                'verbose_name_plural': 'User Action Logs',
                'db_table': 'audit_user_action_log',
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['user', 'timestamp'], name='action_user_time_idx'), models.Index(fields=['action_type'], name='action_type_idx'), models.Index(fields=['user', 'action_type'], name='action_user_type_idx')],
            },
        ),
    ]
