# Generated by Django 6.0.6 on 2026-06-10 07:16

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('leads', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ImageUpload',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('file_path', models.CharField(help_text='Path to the uploaded image file', max_length=500, verbose_name='File Path')),
                ('file_name', models.CharField(help_text='Original file name', max_length=255, verbose_name='File Name')),
                ('image_type', models.CharField(choices=[('ID_PROOF', 'ID Proof'), ('ADDRESS_PROOF', 'Address Proof'), ('SIGNATURE', 'Signature'), ('DOCUMENT', 'Document'), ('OTHER', 'Other')], help_text='Type of image/document', max_length=20, verbose_name='Image Type')),
                ('image_format', models.CharField(choices=[('JPG', 'JPG'), ('PNG', 'PNG'), ('WEBP', 'WebP'), ('GIF', 'GIF')], help_text='Image file format', max_length=10, verbose_name='Image Format')),
                ('file_size', models.IntegerField(blank=True, help_text='File size in bytes', null=True, verbose_name='File Size')),
                ('width', models.IntegerField(blank=True, help_text='Image width in pixels', null=True, verbose_name='Width')),
                ('height', models.IntegerField(blank=True, help_text='Image height in pixels', null=True, verbose_name='Height')),
                ('thumbnail_path', models.CharField(blank=True, help_text='Path to the generated thumbnail', max_length=500, verbose_name='Thumbnail Path')),
                ('is_compressed', models.BooleanField(default=False, help_text='Whether image has been compressed', verbose_name='Is Compressed')),
                ('original_size', models.IntegerField(blank=True, help_text='Original file size before compression', null=True, verbose_name='Original Size')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('lead', models.ForeignKey(blank=True, help_text='Associated lead', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='images', to='leads.lead', verbose_name='Lead')),
                ('uploaded_by', models.ForeignKey(help_text='User who uploaded the image', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='images_uploaded', to=settings.AUTH_USER_MODEL, verbose_name='Uploaded By')),
            ],
            options={
                'verbose_name': 'Image Upload',
                'verbose_name_plural': 'Image Uploads',
                'db_table': 'imager_image_upload',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='DocumentImage',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('document_type', models.CharField(choices=[('PAN', 'PAN Card'), ('AADHAR', 'Aadhar Card'), ('PASSPORT', 'Passport'), ('DRIVING_LICENSE', 'Driving License'), ('UTILITY_BILL', 'Utility Bill'), ('RENT_AGREEMENT', 'Rent Agreement'), ('PROPERTY_DOCUMENT', 'Property Document'), ('SALARY_SLIP', 'Salary Slip'), ('ITR', 'Income Tax Return'), ('BANK_STATEMENT', 'Bank Statement'), ('OTHER', 'Other')], db_index=True, help_text='Type of document', max_length=30, verbose_name='Document Type')),
                ('document_number', models.CharField(blank=True, db_index=True, help_text='Document/ID number (e.g., PAN, Aadhar, etc.)', max_length=100, verbose_name='Document Number')),
                ('valid_from', models.DateField(blank=True, help_text='Document validity start date', null=True, verbose_name='Valid From')),
                ('valid_till', models.DateField(blank=True, help_text='Document expiry date', null=True, verbose_name='Valid Till')),
                ('verification_status', models.CharField(choices=[('PENDING', 'Pending Verification'), ('VERIFIED', 'Verified'), ('REJECTED', 'Rejected'), ('EXPIRED', 'Expired')], db_index=True, default='PENDING', help_text='Current verification status', max_length=20, verbose_name='Verification Status')),
                ('verified_at', models.DateTimeField(blank=True, help_text='When document was verified', null=True, verbose_name='Verified At')),
                ('rejection_reason', models.TextField(blank=True, help_text='Reason for rejection if rejected', verbose_name='Rejection Reason')),
                ('remarks', models.TextField(blank=True, help_text='Additional remarks about the document', verbose_name='Remarks')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('lead', models.ForeignKey(help_text='Associated lead', on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='leads.lead', verbose_name='Lead')),
                ('verified_by', models.ForeignKey(blank=True, help_text='User who verified the document', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='documents_verified', to=settings.AUTH_USER_MODEL, verbose_name='Verified By')),
                ('image', models.ForeignKey(help_text='Associated image file', on_delete=django.db.models.deletion.CASCADE, related_name='document_records', to='imager.imageupload', verbose_name='Image')),
            ],
            options={
                'verbose_name': 'Document Image',
                'verbose_name_plural': 'Document Images',
                'db_table': 'imager_document_image',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='imageupload',
            index=models.Index(fields=['lead'], name='image_lead_idx'),
        ),
        migrations.AddIndex(
            model_name='imageupload',
            index=models.Index(fields=['image_type'], name='image_type_idx'),
        ),
        migrations.AddIndex(
            model_name='imageupload',
            index=models.Index(fields=['created_at'], name='image_created_idx'),
        ),
        migrations.AddIndex(
            model_name='documentimage',
            index=models.Index(fields=['lead', 'document_type'], name='doc_lead_type_idx'),
        ),
        migrations.AddIndex(
            model_name='documentimage',
            index=models.Index(fields=['document_number'], name='doc_number_idx'),
        ),
        migrations.AddIndex(
            model_name='documentimage',
            index=models.Index(fields=['verification_status'], name='doc_verify_status_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='documentimage',
            unique_together={('lead', 'document_type')},
        ),
    ]
