# Generated by Django 4.2.12 on 2026-06-10 12:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0002_alter_lead_lead_status_leadstatuslog_leadnote_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('imager', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ImageBatch',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(help_text='Name for this image batch', max_length=255, verbose_name='Batch Name')),
                ('description', models.TextField(blank=True, help_text='Optional description of the batch', verbose_name='Description')),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('PROCESSING', 'Processing'), ('COMPLETED', 'Completed'), ('PARTIAL', 'Partially Completed')], db_index=True, default='PENDING', max_length=20, verbose_name='Status')),
                ('total_images', models.IntegerField(default=0, verbose_name='Total Images')),
                ('linked_leads', models.IntegerField(default=0, verbose_name='Linked Leads')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
            ],
            options={
                'verbose_name': 'Image Batch',
                'verbose_name_plural': 'Image Batches',
                'db_table': 'imager_image_batch',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='imagebatch',
            name='campaign',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='image_batches', to='leads.campaign', verbose_name='Campaign'),
        ),
        migrations.AddField(
            model_name='imagebatch',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='image_batches_created', to=settings.AUTH_USER_MODEL, verbose_name='Created By'),
        ),
        migrations.AddField(
            model_name='imageupload',
            name='batch',
            field=models.ForeignKey(blank=True, help_text='Batch this image belongs to', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='images', to='imager.imagebatch', verbose_name='Batch'),
        ),
        migrations.AddIndex(
            model_name='imageupload',
            index=models.Index(fields=['batch'], name='image_batch_idx'),
        ),
        migrations.AddIndex(
            model_name='imagebatch',
            index=models.Index(fields=['status'], name='img_batch_status_idx'),
        ),
        migrations.AddIndex(
            model_name='imagebatch',
            index=models.Index(fields=['campaign'], name='img_batch_campaign_idx'),
        ),
    ]
